# Generated by Django 5.2.5 on 2025-08-15 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
